### ISSUE TITLE
peleffy.utils.toolkits.ToolkitUnavailableException: The required toolkit Amber Toolkit is not available.

### ISSUE THREAD

**Issue by alyhalo** [carlesperez94/frag_pele#70]
Error during installation according to [this guide](https://carlesperez94.github.io/frag_pele/installation.html):

```
conda create -n frag python=3.7 --yes
source activate frag
git clone https://github.com/carlesperez94/frag_pele.git
cd frag_pele
pip install numpy python
python setup.py install
cd frag_pele/example/1W7H_example/
python -m frag_pele.main -cp 1w7h_preparation_structure_2w.pdb -x 1 --steps 1 -sef sequential.conf --pele_eq_steps 1 sequential_frag.conf --cpus 2 --steps 1 --temp 1000000
```

After this:

```
Traceback (most recent call last):
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/frag_pele-3.0.0-py3.7.egg/frag_pele/main.py", line 14, in <module>
    from peleffy.forcefield.selectors import ForceFieldSelector
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/__init__.py", line 1, in <module>
    from .forcefield import *
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/forcefield.py", line 10, in <module>
    from peleffy.forcefield.selectors import ChargeCalculatorSelector
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/selectors.py", line 87, in <module>
    class ChargeCalculatorSelector(object):
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/selectors.py", line 92, in ChargeCalculatorSelector
    from peleffy.forcefield.calculators import (OPLSChargeCalculator,
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/calculators.py", line 6, in <module>
    from simtk import unit
ImportError: cannot import name 'unit' from 'simtk' (/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/simtk/__init__.py)
```

But I solved this error [like this](https://github.com/openmm/openmm/issues/2123) (so I think the guide should be corrected):

`conda install -c conda-forge openmm`

But then after test running I got one more error:

```
Traceback (most recent call last):
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/frag_pele-3.0.0-py3.7.egg/frag_pele/main.py", line 14, in <module>
    from peleffy.forcefield.selectors import ForceFieldSelector
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/__init__.py", line 1, in <module>
    from .forcefield import *
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/forcefield.py", line 10, in <module>
    from peleffy.forcefield.selectors import ChargeCalculatorSelector
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/selectors.py", line 87, in <module>
    class ChargeCalculatorSelector(object):
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/selectors.py", line 92, in ChargeCalculatorSelector
    from peleffy.forcefield.calculators import (OPLSChargeCalculator,
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/calculators.py", line 11, in <module>
    class _PartialChargeCalculator(object):
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/forcefield/calculators.py", line 19, in _PartialChargeCalculator
    _amber_toolkit = AmberToolkitWrapper()
  File "/Users/alisagorislav/opt/anaconda3/envs/frag/lib/python3.7/site-packages/peleffy-1.4.3-py3.7.egg/peleffy/utils/toolkits.py", line 983, in __init__
    + 'available.')
peleffy.utils.toolkits.ToolkitUnavailableException: The required toolkit Amber Toolkit is not available.
```

Is there any way to solve it?

I use macOS Monterey 12.1

**Comment by xy127** [comment]
Did you solve the error

**Comment by alyhalo** [comment]
> Did you solve the error

No
